spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
#    url: jdbc:mysql://localhost:3306/atguigudb # For windows
    url: jdbc:mysql://localhost:3306/ssm # For mac
    username: root
    # For Windows
#    password: abc123
    # For Mac
    password: jiangui.1
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      filters: stat,wall # 底层开启功能,stat(sql监控),wall(防火墙)
      aop-patterns: com.atguigu.admin.* # 监控SpringBean
      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: 123
        reset-enable: false
      web-stat-filter: # 监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat: # 对上面Filters里面的stat的详细配置
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  #    filters: stat,wall
#    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3

# 配置mybatis规则
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration: # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true


